### ISSUE TITLE
can't find a way to set enable_pii to True

### ISSUE THREAD

**Issue by MortalViews** [AzureAD/azure-activedirectory-library-for-python#114]
probably am missing something, but i couldn't find a way to set enable_pii =True. 
unless directly setting authContext._call_context['enable_pii']=True

won't it be better to introduce an options kwargs, and merge it with GLOBAL_ADAL_OPTIONS? 
and fetch it from there? 

i can create a PR with the changes.

**Comment by rayluo** [comment]
Thanks for looking into the pii PR #111 and coming up with such question, @MortalViews . It is true that the current usage pattern is less obvious, partially because we thought its usage would be infrequent. On a related note, can we know your usage scenario about how you would use pii? Feel free to chime in here, or shoot me an email if you want to discuss privately.

**Comment by rayluo** [comment]
So we are closing this issue. Feel free to reopen it to revive the conversation.
