### ISSUE TITLE
Need support for prompt behavior

### ISSUE THREAD

**Issue by xiaoningning** [AzureAD/azure-activedirectory-library-for-python#134]
C# SDK supports PromptBehavior when calling AcquireTokenAsync.  Nice to have it in Python as well. With this, it will have a nice way to support MFA.  Right now we have to use code flow instead.

This request is to address this issue.
https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/101

**Comment by alex-slover** [comment]
@rayluo Is this under consideration, and if so, is there any ETA? This would be tremendously nice to have to enable certain scenarios for which the .NET SDK is currently a lot more useful.

**Comment by rayluo** [comment]
@xiaoningning et al: [ADAL .Net/C#'s `AcquireTokenAsync(...)` contains many overloads](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext.acquiretokenasync?view=azure-dotnet). Since you mentioned [its `PromptBehavior`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.promptbehavior?view=azure-dotnet), I believe you were talking about one of its flavor that can pop up a browser window, also known as an Interactive Flow.

At this point, the [ADAL Python library you were using, will not receive new features](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/README.md). Its successor, [MSAL Python, is generally available](https://developer.microsoft.com/en-us/office/blogs/microsoft-authentication-libraries-for-java-and-python-are-now-generally-available/), and will soon release the [`acquire_token_interactive()` behavior](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/260). You folks can give it a shot.
