### ISSUE TITLE
Persistent storage of token

### ISSUE THREAD

**Issue by ace-e4s** [AzureAD/azure-activedirectory-library-for-python#184]
Hello @rayluo, I was looking for a way to persistently store a token (e.g. on disk). The use case is to skip login prompt if the refreshToken is valid.

I could not see a clear/simple way to hook into AuthenticationContext, where the token is dumped to disk everytime its updated/refreshed. What would you recommend? Should I do it by extending TokenCache?

Thanks in advance, and keep up the good work 👍

**Comment by rayluo** [comment]
Sorry for not being able to comment on this earlier. This happens to be a tricky topic. ADAL Python does not provide callbacks to dump cache to disk everytime it is updated/refreshed, actually ADAL Python's default cache does not dump its content on disk at all, and that is partially because there might not be a universal format for every scenarios ADAL Python is used.

That being said, there is some DIY style solution. Some of our downstream developers hook the [token serialize()](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/1.2.0/adal/token_cache.py#L95) upon the exit of their program, and persists the content in their own format. It would certainly work for one single app.

Thanks for your patience, and your previous contribution on the thread topic (#123).

**Comment by ace-e4s** [comment]
No worries. We ended up moving to `requests-oauthlib` since we plan to change to Azure AD B2C soon anyway.
