### ISSUE TITLE
Website doesnt prompt for granting privledges

### ISSUE THREAD

**Issue by boykoc** [AzureAD/azure-activedirectory-library-for-python#204]
Using this [example code](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/sample/website_sample.py) and the instructed setup a user is prompted to login but is never prompted to grant the application privledges. 

This results in an error for first time users using Azure Active Directory Graph when setting required access in azure ad as they never grant access to read their profile and sign in.

If I use Microsoft Graph it prompts for privldege access but then gives an error when it calls the reply URL(the user or admin has not consented to use the application). If a user signs in again it authenticates properly.

Once a user has consented everything works fine. It's allowing them to consent or returning an access token after they consent that proves difficult.

Has this come up before or sound familiur?

**Comment by rayluo** [comment]
This does not sound familiar. In particular, "If I use Microsoft Graph *it prompts for privldege access but then gives an error when it calls the reply URL (the user or admin has not consented to use the application)*" sounds like the consent did not happen.

Nonetheless, the [example code](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/sample/website_sample.py) that you referred to, was written on top of Python's built-in http server, which is not widely used in the wild, thus might not be close enough to your real app. You might want to try our different, more polished [MSGraph-and-ADAL-Python sample here](https://github.com/microsoftgraph/python-sample-auth/blob/master/sample_adal.py).

By the way, some info not directly related to your question:
* [AAD Graph is being deprecated](https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-or-azure-ad-graph/)
* There is also an ADAL Python's successor, [MSAL Python and its website sample here](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/authorization-code-flow-sample/authorization_code_flow_sample.py).

**Comment by boykoc** [comment]
Thanks for this information. I'm going to test out a few things, including the new MSAL python.  I'll loop back with my findings.

On the Microsoft Graph part. I agree, it seems as if the consent did not happen however, once the user tries to login again they are logged in properly and in Azure AD App Registration I can see the new user was added under Permissions -> User Consent tab.

**Comment by rayluo** [comment]
A quick comment on the "If I use Microsoft Graph *it prompts for privldege access but then gives an error when it calls the reply URL (the user or admin has not consented to use the application)*".

* If the error really happens on calling the reply URL (which can be observed by the URL in your browser), but somehow could not reach it, it could be caused by incorrect redirect_uri setting of your app, and/or your web app was not serving that redirect_uri perhaps due to wrong path or port etc..

* But if you are literally seeing some sort of "the user or admin has not consented to use the application" legit error page, and then the next login would be successful, that would sound like an issue from the AAD web-based interaction. A screenshot might be helpful to describe the situation for us to determine next steps.

**Comment by boykoc** [comment]
I've been testing various things to try and figure out what the issue is. 

**I think it boils down to how I was trying to use ADAL to authenticate a user for a website.** 

I had set my `RESOURCE` to the `CLIENT_ID `so that the `access_token `would have an audience of the `CLIENT_ID`.

This works if a user has already consented. If they have not yet, it has issues. But different samples have slightly different results. this is a part that confuses me (why does it partially work?).

My Goal was to authenticate a user with ADAL (or MSAL). I think this is still what is happening but in most cases it is expected that I would authenticate the user and then get an access_token to use to make a call to another API to get more information on on behalf of the user (e.g. ADAL authenticates the user, then gives an access_token the CLIENT_ID can use to get more information about the user from Microsoft Graph).  

# API Permissions with my own custom code

## Azure Active Directory Graph

- This doesn't seem to prompt a user for consent. 
- If a user has previously consented it works fine and I can decode/validate the JWT with pyjwt.
- If a user has not consented it does not prompt them but instead goes to reply URL and gives an error.

## Microsoft Graph

- This prompts a user for consent.
- After a user consents it sends them to the reply url with an error `<BadRequestKeyError '400: Bad Request'>`
- If a user signs-in again, it works fine and I can see the consent took place in Azure AD after the first attempt.

## Both Microsoft Graph and Azure Active Directory Graph

- This prompts a user for consent.
- After a user consents it sends them to the reply url with an error `administrator has not consented to use the application with ID \\'id\\' named \\'resourcename\\'. Send an interactive authorization request for this user and resource.`
- If a user signs-in again, it works fine and I can see the consent took place in Azure AD after the first attempt.
- In this case they see 2 permissions to consent to.

# Specific Examples

## [MSAL Python Website Sample](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/authorization-code-flow-sample/authorization_code_flow_sample.py)

- The audience of the access_token is graph but the audience of id_token is my app client_id
- MSAL returns an [`id_token`](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens) that I could use instead of an [`access_token`](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens)

## [Microsoft Graph API, leveraging ADAL Python](https://github.com/Azure-Samples/active-directory-python-webapp-graphapi)

- If I change /getAToken to `return flask.render_template('display_graph_info.html', graph_data=token_response)`
- And change the Resource in config.py to the app id (client id).
- For an already consented user it works fine. 
- If a user hasn't consented yet it throws `BadRequestKeyError: 400 Bad Request: KeyError: 'code'` from line 44 `code = flask.request.args['code']`.
- If I change the resource back to `https://graph.microsoft.com` it works but this also makes the audience `https://graph.microsoft.com` as well and not the app ID.

## [Sample ADAL ms graph](https://github.com/microsoftgraph/python-sample-auth/blob/master/sample_adal.py)

- `BadRequestKeyError: 400 Bad Request: KeyError: 'code'` if I change the resource to my CLIENT_ID
- URL error `https://url_here/login/authorized?error=invalid_request&error_description=AADSTS90008%3a+The+user+or+administrator+has+not+consented+to+use+the+application+with+ID+%id_here%27.+This+happened+because+application+is+misconfigured%3a+it+must+require+access+to+Windows+Azure+Active+Directory+by+specifying+at+least+%27Sign+in+and+read+user+profile%27+permission............`

**Comment by boykoc** [comment]
WOW! Looking at the last sample I decided to try and figure out what this placeholder was [`GRAPH_RESOURCE = '00000002-0000-0000-c000-000000000000'`](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/3581edf8b2df9e91553abed2dc57336c367f8cb0/sample/website_sample.py#L55) and the only place I could find something like it was in the Azure AD app registration Manifest.

I decided to try it and guess what!  It worked.  so this whole time I've been putting my own "Application (client) ID" in there or I've used the graph url of https://graph.microsoft.com/.

I still have questions but this is the first time it's worked from start to finish (login, consent, JWT that can be validated).

- Shouldn't the audience be for my app?
- why did it work with my app id for already consented users?
- why did it error after consenting with MS Graph but still add the consent in Azure AD and let users in the second time they try logging in?
- moving forward should I really just be using MS Graph with MSAL Python and use / validate the id_token to just authenticate a user?

**Comment by rayluo** [comment]
Well that was intense. :-)  But glad that you seem to have a happy ending.

> Shouldn't the audience be for my app?

No. In the OAuth2 model, you obtain an access token because your app wants to access a resource (which is other than your app). So, you use that resource's identifier in the `resource` parameter when you are using ADAL, or you use some scope(s) identifier in the `scopes` parameter when you are using MSAL. Either way, those actual identifier are defined and documented by the resource. They can be any form, possibly with some equivalent alias, you need to find it from their documentation. The issed access token will contain the proper audience, but nonetheless your app won't even need to care about that, because the access token is not mean to be consumed by your app, at all.

When your app also wants to authenticate an end user, your app will require for an id token, which is already the built-in behavior in ADAL and MSAL. This time, the id token will indeed contain an audience as YOUR app, but you still do NOT need to explicitly set your own app id as the resource or scope. You can just look into the id token and get everything you want.

> moving forward should I really just be using MS Graph with MSAL Python and use / validate the id_token to just authenticate a user?

Yes, those are the future. And, in MSAL Python, we decode and validate the id token for you.

**Comment by boykoc** [comment]
@rayluo Thank you very much for this information and taking the time to guide me through.

I will be moving over to MSAL but still good to see how to handle it in ADAL.  thanks for making the connections to [MSAL issue 13 as well](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/13).
