### ISSUE TITLE
AuthenticationContext is not pickleable

### ISSUE THREAD

**Issue by danield137** [AzureAD/azure-activedirectory-library-for-python#211]
One of our users [has pointed out](https://github.com/Azure/azure-kusto-python/pull/152/files#r304982121) that while trying to use the kusto python client with multi-process map operator, it fails due to the fact that AuthenticationContext is not pickleable.

I am not sure if this is by mistake or by design and I don't want to add overriding code on my end before I know the reason for sure .

If there is no underlying reason here, I will gladly open a PR with the suggested change.

**Comment by rayluo** [comment]
Interesting topic. :-)

I don't think it was "by mistake". [Not all Python objects are picklable anyway](https://docs.python.org/2/library/pickle.html#what-can-be-pickled-and-unpickled). In general, you won't just assume any high-level, non-primitive class to be picklable, unless its doc explicitly says so.

It is not exactly "by design", either. It originally happened to be in that way, and nobody had a problem with that before, although now I understand that in multi-process parallism, pickling is the default behavior (but the official doc still suggests that ["Better to inherit than pickle/unpickle"](https://docs.python.org/2/library/multiprocessing.html#all-platforms)).

We had not tried to pickle AuthenticationContext to see which/how many of its members were causing it to be unpicklable. In practice, the creation of AuthenticationContext itself is largely lightweight. And that PR @danield137 referencing to, is essentially doing exactly that: it merely creates a new AuthenticationContext instance each time. That can still be a legit workaround in your scenario.

The bigger uncertainty might actually be the TokenCache instance. It is conceptually a mini database, and usually you don't "pickle" a database. This might immediately be a problem in ADAL Python where the default TokenCache is just an in-memory json blob (therefore that Kusto Client Python PR still works), but for examle in the world of [MSAL Python](https://github.com/AzureAD/microsoft-authentication-library-for-python), there are [more](https://msal-python.readthedocs.io/en/latest/#tokencache) and [even more sub-classes of TokenCache](https://github.com/AzureAD/microsoft-authentication-extensions-for-python) (which are designed to lock a file on disk so that they can be shared among processes). So a hardcoded `cache = TokenCache(pickled_string)` approach is not unpickling the exact sub-class instance. If we have to do it in this upstream repo (or in MSAL Python repo), we will have to do it in a bullet-proof way, probably by examining and making each and every class there natively picklable.

I think @danield137 can still go ahead to test and approve the pickle workaround in that Kusto Python Client PR, as long as it can work in your scenario. If you want to work out a PR here in ADAL Python, I would suggest that you try that on MSAL Python, as we now tend to NOT introduce any new features into ADAL Python anymore.
