### ISSUE TITLE
oauth token does not have necessary scopes to complete the request

### ISSUE THREAD

**Issue by HahaLun** [AzureAD/azure-activedirectory-library-for-python#212]
I was using adal to retrieve token and access my onenote. The token worked well before 2019-08-07 , but now i get the error indicating the access token did not have necessary scopes to get onenote notes.

the function I have been using are 
1. adal.AuthenticationContext
2. context.acquire_token_with_client_credentials

error": {
    "code": "40004",
    "message": "The OAuth token provided does not have the necessary scopes to complete the request. Please make sure you are including one or more of the following scopes: Notes.ReadWrite.All,Notes.Read.All",
    "innerError": {
      "request-id": "bb5ddb12-ae31-4a44-9af6-72a10cea7e41",
      "date": "2019-08-08T08:10:42"
    }
  }
}

**Comment by rayluo** [comment]
What was the value of resource parameter you used to access OneNote? Nonetheless, now it sounds like the OneNote now requires more "scopes" for a token to work.

One thing though. The ADAL Python you are currently using, talks to AAD v1 endpoint which accepts a "resource" parameter. But in [AAD v2, it expects a "scope" concept](https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-endpoint-comparison#scopes-not-resources). Indeed [our next generation of SDK, the MSAL Python, accepts a scope parameter](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/confidential_client_secret_sample.py#L53) rather than "resource".

Now that you see an error message relayed by ADAL Python, from AAD v1 endpoint, to suggest you to use some `scopes`, that is strange, and makes me feel that you might need/have to switch to MSAL Python to make it work.

**Comment by HahaLun** [comment]
the resource parameter i used was
RESOURCE = 'https://graph.microsoft.com/'

thanks for your help, i will test the MSAL package first

**Comment by rayluo** [comment]
Closing this issue here. Feel free to contact us at the [MSAL Python repo](https://github.com/AzureAD/microsoft-authentication-library-for-python), should you encounter issues on that library.
