### ISSUE TITLE
ADAL-basics Wiki page - typo in code

### ISSUE THREAD

**Issue by bodiz** [AzureAD/azure-activedirectory-library-for-python#218]
One the ADAL-basics Wiki page, a space is missing from the sample code - preventing authentication in its current form.

The 'Bearer' string and the actual token should be separated by a space:
`SESSION.headers.update({'Authorization': "Bearer " + token_response['accessToken']})`

**Comment by rayluo** [comment]
Thanks for reporting this, @bodiz ! I believe you mean [this section](https://github.com/AzureAD/azure-activedirectory-library-for-python/wiki/ADAL-basics#usage). I fixed it just now.

By the way, if you are just starting a new project, you better try our latest authentication library, [MSAL for Python](https://github.com/AzureAD/microsoft-authentication-library-for-python), instead of ADAL Python.

**Comment by bodiz** [comment]
Thanks @rayluo for pointing us to the new authentication library - we are starting a new project, so this is very helpful.
