### ISSUE TITLE
Pass Resource parameter as a String in AuthenticationContext.acquire_token_with_authorization_code

### ISSUE THREAD

**Issue by Sherry112** [AzureAD/azure-activedirectory-library-for-python#235]
Hello,
I need to pass the Resource parameter in ADAL AuthenticationContext.acquire_token_with_authorization_code as a string parameter (i.e. I want to pass the client-id in Resource field). However, this parameter can only be passed as a URI field.

This option is available in ADAL for Android but not available for Python.
Can you please explain what the resource parameter is and how can I do this.

Thanks in advance.
![Screenshot (32)_LI](https://user-images.githubusercontent.com/19520214/85283056-2bc31f00-b4a6-11ea-889d-cc4e4c5748b9.jpg)
![Uploading Screenshot (33)_LI.jpg…]()

**Comment by rayluo** [comment]
It is only documented as "A URI" because most resource looks like a URI, but [that parameter's type is just a string](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/1.2.4/adal/authentication_context.py#L189-L190). You can go ahead and pump in a value you see fit, and see how it goes. :-)

By the way, thanks for your screenshot, which reminds us that [we would need to somehow update that docs.microsoft.com page there](https://docs.microsoft.com/en-us/python/api/overview/azure/activedirectory/client?view=azure-python) to reflect our [recent notice on this repo's homepage](https://docs.microsoft.com/en-us/python/api/overview/azure/activedirectory/client?view=azure-python):

> This library, ADAL for Python, will no longer receive new feature improvements. Instead, use the new library [MSAL for Python](https://github.com/AzureAD/microsoft-authentication-library-for-python).
>
> *    If you are starting a new project, you can get started with the MSAL Python docs for details about the scenarios, usage, and relevant concepts.
> *    If your application is using the previous ADAL Python library, you can follow this migration guide to update to MSAL Python.
> *    Existing applications relying on ADAL Python will continue to work.

**Comment by henrik-me** [comment]
@rayluo @navyasric : ETA on getting the doc updated?

**Comment by rayluo** [comment]
Chatted with Abhi who handled the update of that doc before, and she kindly agreed to take care of this doc update. Thanks Abhi!
