### ISSUE TITLE
Problem generating bearer token using APIs

### ISSUE THREAD

**Issue by satyamchaturvedi** [AzureAD/azure-activedirectory-library-for-python#239]
![image](https://user-images.githubusercontent.com/29769158/92598884-156b7900-f2c7-11ea-9cfc-de71eae395de.png)

how to generate this bearer token (highlighted) programmatically using APIs?
authority_url = 'https://login.microsoftonline.com/' + TENANT_ID
context = adal.AuthenticationContext(authority_url)
Using the ADAL module in python it returns an access token but it does not work, while the one generated in the image on Microsoft docs pages works perfectly fine.
Can someone help me understand, how it works??

**Comment by rayluo** [comment]
In order to acquire a valid token, you would need more info that just `authority_url`.

By the way, this ADAL library no longer receives any new feature updates. We would recommend you to explore our another library, MSAL Python, and this is [one of MSAL Python's sample which demonstrate what kind of configuration you would need](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.5.0/sample/device_flow_sample.py#L2-L13).

If you have follow-up usage question, [Stackoverflow with proper tagging](https://stackoverflow.com/search?q=%5Bmsal%5D+and+%5Bpython%5D+or+%5Badal%5D+and+%5Bpython%5D) is also a good place to ask question. Our support engineers are quite active there, too. As you can see, most of historical questions were answered.

CC: @navyasric @abhidnya13
