### ISSUE TITLE
Continuous OSS-Fuzz integration

### ISSUE THREAD

**Issue by DavidKorczynski** [AzureAD/azure-activedirectory-library-for-python#263]
@rayluo we would be happy to do some fuzzing of ADAL similar to MSAL, are you okay with this? We have done an initial pass here https://github.com/google/oss-fuzz/pull/8000 -- Could we reuse the email address? https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/486

**Comment by rayluo** [comment]
Closing this issue, because ADAL Python already reaches its end-of-life.

In fact, it feels we did not get much benefit from the OSS-Fuzz test for MSAL Python. The fuzz test may be useful for a local library, but how do we make sure the random fuzz test cases do not stress test our backend server? We can continue this conversation separately, perhaps in that [MSAL Python fuzz issue](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/486).
