### ISSUE TITLE
Azure: The access token has been obtained from wrong audience or resource '00000002-0000-0000-c000-000000000000'

### ISSUE THREAD

**Issue by hoaphumanoid** [AzureAD/azure-activedirectory-library-for-python#43]
When using the code of [client credential sample ](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/sample/client_credentials_sample.py) I get this error:

`azure.common.AzureHttpError: {"error"{"code":"AuthenticationFailed","message":"The access token has been obtained from wrong audience or resource '00000002-0000-0000-c000-000000000000'. It should exactly match (including forward slash) with one of the allowed audiences 'https://management.core.windows.net/','https://management.azure.com/'."}}  `

To solve it I changed the parameter:
`RESOURCE = '00000002-0000-0000-c000-000000000000'`
to
`RESOURCE = 'https://management.core.windows.net/'`

**Comment by yugangw-msft** [comment]
The sample shows to get a token from the graph resource, one of many azure resources. The token for one resource doesn't mean it can be used to access other resources, say the management resource in your case.
So it is by design.
However, the refresh token under your case can be used to exchange for a new access token for management resource. Check out this [sample](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/sample/refresh_token_sample.py#L60), you need to replace `RESOURCE` to the management url.

**Comment by hoaphumanoid** [comment]
@yugangw-msft Hi I think you should explain this better. There is no way for the user to know. I found the solution by pure change looking at stackoverflow. I suggest that you add some comment in the code to explain this.
