### ISSUE TITLE
Expand Resiliency Error Codes

### ISSUE THREAD

**Issue by kgidewall** [AzureAD/azure-activedirectory-library-for-python#70]
We currently invoke resiliency mode when the following conditions occur: network timeout or http error codes 500, 503, 504. After discussion, we have decided to expand the error code list to include ALL http error codes 500 - 599. Please change your logic to include all of those codes for Resiliency.

**Comment by rayluo** [comment]
Closing this due to 3 reasons:

* At this point, ADAL Python no longer receives any new changes except bugfixes.
* In the successor, the MSAL Python, we headed to a different direction anyway: errors and http errors could be retried in http layer (by a customized http client), and/or eventually being raised as exceptions.
* Recently, [MSAL Python also implemented a resiliency feature](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/159) which focuses on not overloading the AAD service.
