### ISSUE TITLE
Refresh Token does not work - Transmission data parser failure

### ISSUE THREAD

**Issue by JuaSmithy** [AzureAD/azure-activedirectory-library-for-python#81]
I've followed the refresh_token sample provided, below are an extract of my code: 

context = adal.AuthenticationContext(authority=(authority + tenant_id), validate_authority=False)
token = context.acquire_token_with_client_credentials(resource_id, client_id, client_secret)
print(token)
refresh_token = token['accessToken'] 
print(refresh_token)
token = context.acquire_token_with_refresh_token(refresh_token, client_id, resource_id)

Firstly command refresh_token = token['refreshToken'] fail, I assume you meant 'accessToken' ?
Last command fail with below:

AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS70000: Transmission data parser failure: Refresh Token is malformed or invalid.\r\nTrace ID: 52e91e1c-6ee0-40b8-b3f8-546b8be4fbad\r\nCorrelation ID: 6e9b6654-a911-44f3-9f40-f26555f4df30\r\nTimestamp: 2017-03-15 14:08:19Z","error_codes":[70000],"timestamp":"2017-03-15 14:08:19Z","trace_id":"52e91e1c-6ee0-40b8-b3f8-546b8be4fbad","correlation_id":"6e9b6654-a911-44f3-9f40-f26555f4df30"}

How to correct this error ?

What should I enter in these parameters exactly ? Below is what I used

"resource": "'https://management.core.windows.net",  - is this default correct to use ?
"tenant" : I entered the tenant id from app in active directory ?
authorityHostUrl" : "https://login.microsoftonline.com" - is this correct to use ?

**Comment by rayluo** [comment]
Looks like you are actually using Client Credentials Grant, so you do not need to deal with refresh token. You just follow this Client Credential sample. https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/sample/client_credentials_sample.py

**Comment by JuaSmithy** [comment]
Dear Rayluo, thank you for your quick response.
Using the Client Credential method to authenticatete, caused indeed a timeout in the Webjob where the python code was scheduled after 1 hour. 
See attached the job log of the failure
[__testpythonautomation.scm.azurewebsites.net_vfs_data_job.pdf](https://github.com/AzureAD/azure-activedirectory-library-for-python/files/846959/__testpythonautomation.scm.azurewebsites.net_vfs_data_job.pdf)

Please can you also confirm if above parameters are correct.
I registered an app in active directory and are using webjobs to run the script.

**Comment by rayluo** [comment]
Yes, the access token will typically be short-lived. But this would not be a problem, if you (and you are supposed to) redo the same Client Credentials Grant again at a later time. Actually you redo it whenever the previous access token becomes invalid.

**Comment by JuaSmithy** [comment]
Dear Ray Luo
I'm confused, you are saying above that for Client Credentials no token
refresh is needed, and last message that the token is short-lived. Which
one is it ?
Why should clients have to worry about token refresh and why is it not
included in the SDK ?
Can you please give an example how the refresh token should be coded  and
how to check when it expires.
I tried several options, spend many days, but cannot get it work.
Kind regards

**Comment by rayluo** [comment]
Well, I guess you confuse the two things:

* A short-lived token named Access Token (AT), which is used to access the real resource you want. Since it is short-lived, you will need to somehow "refresh" it periodically.
* A long-lived token named Refresh Token (RT), which is only used for obtaining a new access token.

Those are concepts defined in OAuth2.

Since you are using `acquire_token_with_client_credentials()` to get an access token to representing your app, it will give you an access token (AT) good for typically one hour, WITHOUT a long lived refresh token (RT). And that behavior is by definition/by design, per [OAuth2 spec on Client Credential Grant](https://tools.ietf.org/html/rfc6749#section-4.4.3). So, you are supposed to somehow persist your app's client_id and credential, and call `acquire_token_with_client_credentials()` again to get a new AT, whenever needed.
