### ISSUE TITLE
Update sample with api_version=None

### ISSUE THREAD

**Issue by lmazuel** [AzureAD/azure-activedirectory-library-for-python#90]
To avoid warning when we follow meticulously the sample:
```bash
D:\VSProjects\azure-sdk-for-python\env3.5\lib\site-packages\adal\authentication_context.py:88: DeprecationWarning: The default behavior of including api-version=1.0 on the wire
                is now deprecated.
                Future version of ADAL will change the default value to None.

                To ensure a smooth transition, you are recommended to explicitly
                set it to None in your code now, and test out the new behavior.

                    context = AuthenticationContext(..., api_version=None)

  """, DeprecationWarning)
```

**Comment by rayluo** [comment]
Thanks for your suggestion @lmazuel !  We chose to NOT modify samples when [we introduced that DeprecationWarning](https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/57), because we considered the explicit `api_version=None` flag as a temporary solution and it would not be necessary once we adopt the `api_version=None` behavior by default in next major release.

That being said, it becomes clear that we don't have any other breaking changes in the backlog, so the next major release won't be available anytime soon. I will go ahead and modify all current samples as you suggested. Stay tuned.
